###
POST http://localhost:8089/api/batch/traffic-density/download?url=https://data.ibb.gov.tr/dataset/3ee6d744-5da2-40c8-9cd6-0e3e41f1928f/resource/bedd5ab2-9a00-4966-9921-9672d4478a51/download/traffic_density_202411.csv

###
POST http://localhost:8089/api/batch/traffic-density/run
